### ISSUE TITLE
Remove Codeapprove image once PR is approved.

### ISSUE THREAD

**Issue by rockwotj** [codeapprove/feedback#65]
GitHub recently announced new options for [controlling the commit message](https://github.blog/changelog/2022-08-23-new-options-for-controlling-the-default-commit-message-when-merging-a-pull-request/) when PRs are merged. We use squash and merge, and the actual commits people make are mostly useless, so we've started defaulting to the Pull Request and description as the commit when squashed into master. The problem with that is that now we're getting the review image and label in our commits on master, which makes reading the commits that have happened very noisey. 

Most commits on master end with:

```
<a data-ca-tag
    href="https://codeapprove.com/pr/<redacted>"><img
    src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review
    on CodeApprove" /></a>
```

Which is a ton of noise. When a PR is approved in Code Approve could that badge be automatically removed? Or at least turn it into something more text friendly at the latest.

If you're unwilling to remove the link on approval, can you at least update the link to be markdown instead of HTML?

```markdown
[![Review on CodeApprove](https://codeapprove.com/external/github-tag-allbg.png)](https://codeapprove.com/pr/<redacted>)
```

If you need the `data-ca-tag` to hide it with CSS on codeapprove.com I'd suggest changing your selector to:

```css
img[alt="Review on CodeApprove"] {
  display: none;
}
/* or even add the src to be super explicit */
img[alt="Review on CodeApprove"][src="https://codeapprove.com/external/github-tag-allbg.png"] {
  display: none;
}
```

That will hide the image, and since the image is gone the link won't be clickable either.
