### ISSUE TITLE
Style: Reduce margins for sub-lists

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#95]
To me, lists within lists have an awkward amount of y-axis padding:

![image](https://user-images.githubusercontent.com/7783288/232121521-5dd55fb2-6cf3-4d49-99a5-efdd597f4958.png)

Would you consider a rule like this?

```css
li ul {
  margin-top: 0;
  margin-bottom: 0;
}
```

That should result in lists that look like this:

![image](https://user-images.githubusercontent.com/7783288/232121929-e385db23-7815-4dc9-8982-9a6b047ccc6a.png)
